version: '2'
services:
  myapp:
     build: .
     volumes:
         - .:/src:rw
     ports:
         - 3000:3000
     links:
         - mongodb
     depends_on:
         - mongodb
  mongodb:
     image: mongo:latest
     environment:
       - MONGO_DATA_DIR=/data/db
       - MONGO_LOG_DIR=/dev/null
     volumes:
       - ./data/db:/data/db
     ports:
         - 27017:27017

